# Generated by Django 4.0.4 on 2022-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_feature_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='content',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='feature',
            name='location',
            field=models.CharField(default='nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='weather',
            field=models.CharField(default='hot', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(default='9/02/2000'),
        ),
    ]
