# Generated by Django 4.0.4 on 2022-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_feature_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='region',
            field=models.CharField(default='central', max_length=100),
        ),
    ]
