# Generated by Django 4.0.4 on 2022-05-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='post.region'),
        ),
    ]
