# Generated by Django 4.0.4 on 2022-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_feature_region_delete_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='location',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='weather',
        ),
        migrations.AddField(
            model_name='feature',
            name='nearby_town',
            field=models.CharField(default='kiambu', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='experience',
            field=models.CharField(max_length=1000),
        ),
    ]
